In [ ]:
from matplotlib.collections import LineCollection
from matplotlib.colors import Normalize
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


np.random.seed(0)
n = 100
x = np.linspace(0, 10, n)
y = np.sin(x) + np.random.normal(0, 0.2, n)
weights = np.abs(np.random.normal(0, 1, n))

# Create a DataFrame and sort by x
df = pd.DataFrame({'x': x, 'y': y, 'weight': weights})
df = df.sort_values('x')

# Create a line collection
points = np.array([df['x'], df['y']]).T.reshape(-1, 1, 2)
segments = np.concatenate([points[:-1], points[1:]], axis=1)

# Create the figure and axis
fig, ax = plt.subplots(figsize=(12, 6))

# Create a continuous norm to map from data points to colors
norm = Normalize(df['weight'].min(), df['weight'].max())
lc = LineCollection(segments, cmap='viridis', norm=norm)

# Set the values used for colormapping
lc.set_array(df['weight'])
lc.set_linewidth(2)

# Add the collection to the axis
line = ax.add_collection(lc)

# Set the axis limits
ax.set_xlim(df['x'].min(), df['x'].max())
ax.set_ylim(df['y'].min(), df['y'].max())

# Add a colorbar
cbar = fig.colorbar(line, ax=ax)
cbar.set_label('Weight')

# Customize the plot
ax.set_title('Weighted Lineplot')
ax.set_xlabel('X-axis')
ax.set_ylabel('Y-axis')

plt.tight_layout()
plt.show()

In [13]:
import numpy as np

np.full(2500, 0)

array([0, 0, 0, ..., 0, 0, 0])

In [4]:
import pickle

with open("../data/insectsound/insectsound_train.pkl", 'rb') as f:
    traindata = pickle.load(f)

with open("../data/insectsound/insectsound_test.pkl", 'rb') as f:
    evaldata = pickle.load(f)

evaldata["labels"]

['Aedes_female',
 'Aedes_male',
 'Fruit_flies',
 'House_flies',
 'Quinx_female',
 'Quinx_male',
 'Stigma_female',
 'Stigma_male',
 'Tarsalis_female',
 'Tarsalis_male']

In [11]:
import numpy as np


a = np.zeros((3,3))

a[0] = np.array([1,2,3])
a[1] = np.array([3,2,1])
a[2] = np.array([1,2,3])

a[: , ::-1]

array([[3., 2., 1.],
       [1., 2., 3.],
       [3., 2., 1.]])

In [9]:
import numpy as np

from sklearn.model_selection import train_test_split

a = np.full(50000, 1)

a, b = train_test_split(a, test_size=0.1, train_size=0.4, random_state=42)

print(a.shape, b.shape)

(20000,) (5000,)


In [9]:
import numpy as np

w = [0.3, 0.1, 0.8, 0.5]

a = np.interp(w, (min(w), max(w)), (0, 1)).round(decimals=3)
a

array([0.286, 0.   , 1.   , 0.571])

In [13]:
import numpy as np

a = [np.array([1,2,3]), np.array([1,2,3]), np.array([1,2,3])]

np.vstack(a).mean(axis=0)

array([1., 2., 3.])

In [24]:
import numpy as np

a = np.array([[[[1], [2], [3], [4], [6], [7], [8], [9]]]])

a.mean()

5.0

In [31]:
import os


os.path.isdir("../explanations")

True